#!/bin/sh
#########################################################################################################################################################################################
##                                                                A U T O L I N U X    B O O T S T R A P    S C R I P T                                                                ##
#########################################################################################################################################################################################

#                                                         _               _               _       __                         _  _                                                      # 
#                                                        /.\     _    _  FJ_     ____    FJ      / J   _ _   _    _    _    FJ  LJ                                                     # 
#                                                       //_\\   J |  | LJ  _|   F __ J  J |      LFJ  J ' \  J   J |  | L   J \/ F                                                     # 
#                                                      / ___ \  | |  | || |-'  | |--| | | |      J  L | |\\   |  | |  | |   /    \                                                     # 
#                                                     / L___J \ F L__J JF |__-.F L__J J F L_____ J  L F L \  JJ  F L__J J  /  /\  \                                                    # 
#                                                    J__L   J__J\____,__\_____J\______/J________LJ__LJ__L \\J__LJ\____,__LJ__//\\__L                                                   # 
#                                                    |__L   J__|J____,__J_____FJ______F|________||__||__L   J__| J____,__F|__/  \__|                                                   # 

#########################################################################################################################################################################################
#########################################################################################################################################################################################

 #-------------------------------#
## ### VARIABLES & FUNCTIONS ### ##
 #-------------------------------#


pkgdir="/opt"

aurhelper="yay"

mirlist="/etc/pacman.d/mirrorlist"

lmirlist="/etc/pacman.d/local-mirrorlist"

dotfiles="https://gitlab.com/qyp/dotfiles.git"


arch="$(uname -m)"

srcdir=$(cd $(dirname ${BASH_SOURCE[0]}) && pwd && echo)

area="$(curl -4 ifconfig.co/country-iso)"           

bootid="$(lsblk|grep boot |sed 's/p.*$//;s/├─//;s/└─//'|sed 's/^/\/dev\//;s/$/\//')"

rmdblck="$([ -f /var/lib/pacman/db.lck ] && rm -rf /var/lib/pacman/db.lck)"


installpkg(){ pacman --noconfirm --needed -S "$*" >/dev/null 2>&1 ; }

check_root(){ [ "$(id -u)" -ne 0 ] && err "Root priviledges are required to run this script!"; }

err(){ echo >&2 "$(tput bold; tput setaf 1)[-] ERROR: ${*}$(tput sgr0)" && $rmdblck ; exit 1337; }


newmirrors(){ \
    dialog --infobox " Testing fastest mirrors for most efficient downloads..." 4 50
    mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup && reflector --sort rate -a48 -f20 -l20 -c 'ZA,US,UK,Germany,Netherlands' \
-p 'http,https' --save /etc/pacman.d/mirrorlist >/dev/null 2>&1  ; }

initmsg1(){ \
	dialog --title " Welcome to Automate OS! " --msgbox "\\n             Welcome, and thank you for choosing AutoLinux!\\n\\n    This script will now install the AutoLinux edition of your choice.\\n" 9 80 ; }

whichedition(){
  edition="$(dialog --colors --menu "   Please Select the AutoLinux Edition to Install :" 12 55 1 1 "DWM                                        " 2 "Plasma                                     " 3 "Bare ArchLinux                             "  3>&1 1>&2 2>&3 3>&1)" ; }

initmsg2(){
	dialog --colors --title " Please Note :" --yes-label " Lets Boogie! " --no-label " Lets not boogie :| " --yesno "\\n  An Arch Linux, or Arch based system is required for the installation of AutoLinux.\\n\\n       If you are running any other distrobution the installation will fail." 9 90 ; }

user_and_password() {
	name=$(dialog --inputbox " Please enter a name for the user account: " 10 60 3>&1 1>&2 2>&3 3>&1) || exit 1
	while ! echo "$name" | grep -q "^[a-z_][a-z0-9_-]*$"; do
		name=$(dialog --no-cancel --inputbox "Username not valid. Give a username beginning with a letter, with only lowercase letters, - or _." 10 60 3>&1 1>&2 2>&3 3>&1)
	done
	pass1=$(dialog --no-cancel --passwordbox "Enter a password for that user:" 10 60 3>&1 1>&2 2>&3 3>&1)
	pass2=$(dialog --no-cancel --passwordbox "Retype the password." 10 60 3>&1 1>&2 2>&3 3>&1)
	while ! [ "$pass1" = "$pass2" ]; do
		unset pass2
		pass1=$(dialog --no-cancel --passwordbox "Passwords do not match.\\n\\nEnter password again." 10 60 3>&1 1>&2 2>&3 3>&1)
		pass2=$(dialog --no-cancel --passwordbox "Retype password." 10 60 3>&1 1>&2 2>&3 3>&1)
	done ; }

root_user_password(){
    pass3=$(dialog --no-cancel --passwordbox "Enter a password for the root user:" 10 60 3>&1 1>&2 2>&3 3>&1)
	pass4=$(dialog --no-cancel --passwordbox "Retype the password." 10 60 3>&1 1>&2 2>&3 3>&1)
	while ! [ "$pass3" = "$pass4" ]; do
		unset pass2
		pass3=$(dialog --no-cancel --passwordbox "Passwords do not match.\\n\\nEnter password again." 10 60 3>&1 1>&2 2>&3 3>&1)
		pass4=$(dialog --no-cancel --passwordbox "Retype password." 10 60 3>&1 1>&2 2>&3 3>&1)
    done ; }

usercheck() { \
	! { id -u "$name" >/dev/null 2>&1; } ||
	dialog --colors --title "WARNING!" --yes-label " CONTINUE " --no-label " RETURN " --yesno "\nThe user '$name' already exists on this system. AutoLinux can install for this user, but will overwrite any existing configuration files existing on \\nthis users account. \\n\\nHowever, it will not overwrite any other user files, documents, videos, or personal files of any sorts.\\n\\nIrrespective, only click <CONTINUE> if you are certain you have backed up any wanted system 'config' files.\\n\\nThe users password will also be changed to the one you just provided." 17 85 ; }

preinstall() { \
	dialog --title " The calm before the STORM!" --yes-label "CONTINUE" --no-label " EXIT " --yesno "\\nThe rest of the proccess is automated and might take a while, depending on your connection. \\n\\nSo sit back, relax and please do not stop the process if it seems stuck.\\n\\nSome packages just take longer to compile than others.\\n\\n\\n  Ready when you are?" 16 60 ; }


adduserandpass() { \
	dialog --infobox " Adding user \"$name\"..." 4 50
	useradd -m "$name"  >/dev/null 2>&1
	usermod -aG wheel,audio,optical,video,kvm,network,adm "$name" && chown $name /home/"$name"  >/dev/null 2>&1
	export repodir="/home/$name/.local/src"; mkdir -p "$repodir"; chown -R "$name":wheel "$(dirname "$repodir")"
	echo "$name:$pass1" | chpasswd >/dev/null 2>&1
	unset pass1 pass2 ; }

setrootpass(){
	dialog --infobox " Changing password for root user..." 4 50
	echo "root:$pass3" | chpasswd >/dev/null 2>&1
	unset pass3 pass4 ; }

bootload(){
    dialog --colors --title " Clean Install or Existing System? " --yes-label " Install GRUB! " --no-label " I have a bootloader. " --yesno "\\n Would you like AutoLinux to install the GRUB bootloader? \\n\\n If it is your first time installing an OS and you have not yet installed or \n configured a bootloader, then selecting 'yes' would be a required for the \n system to function or boot." 11 100 &&
        loader="$?" ; }

addmirrors(){
    dialog --colors --title " Additional Mirrors and Repositories " --yes-label " Yes, Add Them! " --no-label " No Thanks. " --yesno "\\n Would you like to add the additional Mirrors and Repositories to the build?\\n\\n These mirrors would be beneficial as they would give you access/availability to many extra\n resources and repositories to acquire packages and other software.\n\n\n NOTE: Adding these extra mirrors would also significantly speed up the installation process,\n since you will be downloading binary versions of most aur packages, instead of compiling  \n everything from source." 15 100
        yesmir="$?" ; }

chshell(){
chsh -s /bin/zsh >/dev/null 2>&1
chsh -s /bin/zsh "$name" >/dev/null 2>&1
sudo -u "$name" mkdir -p "/home/$name/.cache/zsh/" ; }

refreshkeys() { \
		dialog --infobox "Refreshing Arch Keyring..." 4 40
		pacman --noconfirm -S archlinux-keyring >/dev/null 2>&1
		dialog --infobox "Adding Concise Keyring..." 4 40

  yes|pacman-key --recv-key 3E550ACE369CFA1BEE0ABA6E8C85178C555A3C06 --keyserver keyserver.ubuntu.com >/dev/null 2>&1 
  yes|pacman-key --lsign-key 3E550ACE369CFA1BEE0ABA6E8C85178C555A3C06  >/dev/null 2>&1
  yes|pacman -U 'https://gitlab.com/qyp/concise/-/raw/master/x86_64/concise-keyring-1.0.2-1-any.pkg.tar.zst' >/dev/null 2>&1
	
  cat /etc/pacman.conf|grep -q "^\[concise\]"|| cat << EOF >>/etc/pacman.conf
    
[concise]
SigLevel = Required DatabaseOptional
Server = https://gitlab.com/qYp/\$repo/-/raw/master/\$arch

EOF
  dialog --infobox "Updating Repos and Keys..." 4 40  
  for repo in core extra community multilib; do
  grep -q "^\[$repo\]" /etc/pacman.conf || echo "[$repo]
Include = /etc/pacman.d/mirrorlist
" >> /etc/pacman.conf
done

    pacman-key --init >/dev/null 2>&1 
    pacman-key --populate >/dev/null 2>&1
    pacman -Syy >/dev/null 2>&1
}

sudoers(){ echo -e "\n$*" >> /etc/sudoers ; }

gpudrivers(){ \
    dialog --infobox " Detecting Graphics Card..." 4 40
    local GPU="$(neofetch |grep GPU|sed 's/^\.*.s//' |cut -d" " -f2)"
	
    case $GPU in
        AMD) dialog --infobox " Installing AMD GPU Drivers..." 4 40
	    yes|pacman -S  --needed xf86-video-amdgpu >/dev/null 2>&1 ;;
        NVIDIA)  dialog --infobox " Installing NVIDIA GPU Drivers..." 4 40
	    yes|pacman -S  --needed nvidia-470xx-dkms nvidia-470xx-settings nvidia-470xx-utils >/dev/null 2>&1 ;;
        Intel)   dialog --infobox " Installing Intel GPU Drivers..." 4 40
	    yes|pacman -S --needed vulkan-intel xf86-video-intel intel-gpu-tools >/dev/null 2>&1 ;;
        Radeon) dialog --infobox " Installing Radeon GPU Drivers..." 4 40
	    yes|pacman -S  --needed opencl-mesa vulkan-raedon >/dev/null 2>&1 ;;
             *)  dialog --infobox " Unknown GPU Detected, Skipping GPU Driver Installation..." 4 40 && sleep 2 ;;

    esac; unset x ; }

cpudrivers(){ \
    dialog --infobox " Detecting CPU..." 4 40
    local CPU="$(neofetch |grep CPU |sed 's/^\.*.s//' |cut -d" " -f2)"
    
    case $CPU in
        Intel) dialog --infobox " Installing Intel CPU Drivers..." 4 40
            yes|pacman -S --needed intel-ucode >/dev/null 2>&1 ;;
          AMD) dialog --infobox " Installing AMD CPU Drivers..." 4 40
            yes|pacman -S --needed amd-ucode >/dev/null 2>&1 ;;
            *) dialog --infobox " Unknown CPU Detected, Skipping CPU Driver Installation..." 4 40 ; sleep 2 ;;

    esac ; unset x ; }

replacedir(){ \
    dialog --infobox "Installing AutoLinux custom builds of '$(basename "$1")' ($n of $total).  $2" 5 70
	destdir="/usr/share"
	clonename="$(basename "$1" .git)"
    clonepath="$destdir/$clonename"
	[ -e "$clonepath" ] && sudo mv $clonepath "$clonepath'-old'" ;
	git clone "$1" $clonepath  >/dev/null 2>&1
	cd /tmp || return 1 ; }

archlinuxinstall(){
    dialog --infobox "Installing "$1", an AUR helper..." 4 50
	[ -d "$pkgdir"/"$1" ] && rm -rf "$pkgdir"/"$1" ;
    sudo git clone --depth 1 https://aur.archlinux.org/"$1".git $pkgdir/"$1" >/dev/null 2>&1 ;
	chown "$name":wheel $pkgdir/"$1" ||{ cd "$pkgdir/$1" || return 1 ; sudo -u "$name" git pull --force origin master;}
	cd "$pkgdir/$1"&&sudo -u "$name" makepkg --noconfirm -si >/dev/null 2>&1 || return 1 ; cd /tmp ; }

maininstall(){
	dialog --title "AutoLinux Installation" --infobox "Installing '$1' ($n of $total).   $2" 5 70
	installpkg "$1" ; }

gitinstall(){
	progname="$(basename "$1" .git)"
	dir="$repodir/$progname"
	dialog --title "AutoLinux Installation" --infobox "Cloning and Building '$progname' ($n of $total). '$(basename "$1")' $2" 5 70
	sudo -u "$name" git clone --depth 1 "$1" "$dir" >/dev/null 2>&1 || { cd "$dir" || return 1 ; sudo -u "$name" git pull --force origin master;}
	cd "$dir" || exit 1
	makepkg -sri >/dev/null 2>&1
	cd /tmp || return 1 ; }

gitcompile(){
	progname="$(basename "$1" .git)"
    dir="$repodir/$progname"
	dialog --title "AutoLinux Installation" --infobox "Installing the AutoLinux  build of '$progname' ($n of $total). $(basename "$1") $2" 5 70
	sudo -u "$name" git clone --depth 1 "$1" "$dir" >/dev/null 2>&1 || { cd "$dir" || return 1 ; sudo -u "$name" git pull --force origin master;}
	cd "$dir" || exit 1
	make >/dev/null 2>&1
	make install >/dev/null 2>&1
	cd /tmp || return 1 ; }

aurinstall(){ \
	dialog --title "AutoLinux Installation" --infobox "Installing '$1' ($n of $total) from the AUR. $2" 5 70
	echo "$aurinstalled" | grep -q "^$1$" && return 1
	sudo -u "$name" $aurhelper -S --noconfirm "$1" >/dev/null 2>&1
	}

pipinstall(){ \
	dialog --title "AutoLinux Installation" --infobox "Installing the Python package '$1' ($n of $total). $2" 5 70
	[ -x "$(command -v "pip")" ] || installpkg python-pip >/dev/null 2>&1
	yes | pip install "$1" ; }

installationloop(){ \
	([ -f "$pkgsfile" ] && cp "$pkgsfile" /tmp/editions.csv) || curl -Ls "$pkgsfile" | sed '/^#/d' > /tmp/editions.csv
	total=$(wc -l < /tmp/editions.csv)
	aurinstalled=$(pacman -Qqm)
	while IFS=, read -r tag program comment; do
		n=$((n+1))
		echo "$comment" | grep -q "^\".*\"$" && comment="$(echo "$comment" | sed "s/\(^\"\|\"$\)//g")"
		case "$tag" in
			"A") aurinstall "$program" "$comment" ;;
			"M") gitinstall "$program" "$comment" ;;
			"G") gitcompile "$program" "$comment" ;;
			"P") pipinstall "$program" "$comment" ;;
			"R") replacedir "$program" "$comment" ;;
		     *) maininstall "$program" "$comment" ;;
		esac
	done < /tmp/editions.csv ; }

placeconfigs() {
	dialog --infobox " Downloading and installing config files..." 4 60
	branch="$gitbranch" ; dir=$(mktemp -d)
	[ ! -d "$2" ] && mkdir -p "$2"
	chown "$name":wheel "$dir" "$2"
	sudo -u "$name" git clone --recursive -b "$branch" --depth 1 --recurse-submodules "$1" "$dir" >/dev/null 2>&1
	sudo -u "$name" cp -rfT "$dir" "$2" ; }

systembeepoff() { dialog --infobox "Getting rid of that retarded error beep sound..." 4 40
	rmmod pcspkr >/dev/null 2>&1 & echo "blacklist pcspkr" > /etc/modprobe.d/nobeep.conf >/dev/null 2>&1 ; sleep 2 ; }

promptfix(){ \
    dialog --infobox " Fixing Shell Syntax Coloring Issue..." 4 45
    pacman -R lolcat --noconfirm >/dev/null 2>&1 
    sudo -u $name paru -S --noconfirm python-lolcat >/dev/null 2>&1 ; }

mirrors(){
cd /tmp
    dialog --infobox " Adding ArcoLinux Mirrors and Keys..." 4 50
    sudo wget https://github.com/arcolinux/arcolinux_repo/raw/master/x86_64/arcolinux-keyring-20230919-6-any.pkg.tar.zst -O /tmp/arcolinux-keyring-20230919-6-any.pkg.tar.zst >/dev/null 2>&1
yes |sudo pacman -U --noconfirm --needed /tmp/arcolinux-keyring-20230919-6-any.pkg.tar.zst >/dev/null 2>&1
    sudo wget https://raw.githubusercontent.com/arcolinux/arcolinux-mirrorlist/master/etc/pacman.d/arcolinux-mirrorlist -O /etc/pacman.d/arcolinux-mirrorlist  >/dev/null 2>&1
sed -i '/arcolinux_repo/{N;d}' /etc/pacman.conf; sed -i '/arcolinux_repo_3party/{N;d}' /etc/pacman.conf; sed -i '/arcolinux_repo_xlarge/{N;d}' /etc/pacman.conf ;
echo -e "[arcolinux_repo]\nInclude = /etc/pacman.d/arcolinux-mirrorlist\n\n[arcolinux_repo_3party]\nInclude = /etc/pacman.d/arcolinux-mirrorlist\n\n[arcolinux_repo_xlarge]\nInclude = /etc/pacman.d/arcolinux-mirrorlist\n" >> /etc/pacman.conf ;

    dialog --infobox " Adding Chaotic Mirrors and Keys..." 4 50 &&
yes|pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com >/dev/null 2>&1
yes|pacman-key --lsign-key FBA220DFC880C036 >/dev/null 2>&1
yes|pacman -U \
    'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'  >/dev/null 2>&1 \
    'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' >/dev/null 2>&1 &&
sed -i '/chaotic-aur/{N;d}' /etc/pacman.conf
echo -e "[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist\n" >> /etc/pacman.conf ;

  dialog --infobox " Adding BlackArch Mirrors and Keys..." 4 50  &&
curl -LO blackarch.org/strap.sh >/dev/null 2>&1  &&
echo 46f035c31d758c077cce8f16cf9381e8def937bb strap.sh | sha1sum -c >/dev/null 2>&1  &&
chmod +x strap.sh  ; sudo sh strap.sh >/dev/null 2>&1 &&

  dialog --infobox " Updating System Keys and Mirrors..." 4 50
yes|pacman -Syyu >/dev/null 2>&1 ; }

system_config(){ \
	hostname="AutoLinux"
	dialog --infobox "Setting System Information..." 4 40 ; sleep 2 &&

	grep -q "ILoveCandy" /etc/pacman.conf || sed -i "/#VerbosePkgLists/a ILoveCandy" /etc/pacman.conf
	sed -i "s/^#ParallelDownloads = *.*$/ParallelDownloads = 10/;s/^#Color$/Color/" /etc/pacman.conf
  [ $edition = '3' ] && hostname="ArchLinux" ; [ -f /etc/localtime ] && rm /etc/localtime ;
    ln -sF /usr/share/zoneinfo/Africa/Harare /etc/localtime
	sed -i 's/#en_US.UTF-8/en_US.UTF-8/g' /etc/locale.gen
	sed -i 's/#en_ZA.UTF-8/en_ZA.UTF-8/g' /etc/locale.gen
	sed -i "s/#en_"$area".UTF-8/en_"$area".UTF-8/g" /etc/locale.gen
	echo -e "\nLANG=en_ZA.UTF-8\nLANG=en_US.UTF-8" > /etc/locale.conf &&
    [ "$(cat /etc/locale.conf|grep "$area"|wc -l)" -eq "0" ] && 
    echo "LANG=en_"$area".UTF-8" >>/etc/locale.conf ; locale-gen &>/dev/null
	echo -e "127.0.0.1     localhost\n::1     localhost\n127.0.1.1     $hostname.localhost $hostname" >/etc/hosts
    [ $edition = "2" ] && systemctl enable sddm.service >/dev/null 2>&1 ; systemctl enable NetworkManager.service >/dev/null 2>&1 ; 
    [ $edition = '1' ] || [ $edition = '2' ] && systemctl enable bluetooth-autoconnect.service >/dev/null 2>&1 ; 
    systemctl enable bluetooth.service >/dev/null 2>&1 ; [ $edition = "1" ] && 
      systemctl enable mpd.service >/dev/null 2>&1 ; echo "$hostname" > /etc/hostname
  rm -rf /tmp/pulse* ~/.pulse* ~/.config/pulse /home/$name/.pulse* /home/$name/.config/pulse* ; }

xftlib(){ \                                            
    dialog --title "AutoLinux Installation" --infobox "Lastly installing 'libxft-bgra' .\nSuckless software to display color emojis without causing any errors." 6 80
    ! pacman -Qq libxft-bgra >/dev/null 2>&1 && pacman -R --noconfirm libxft-bgra >/dev/null 2>&1 ;
    yes | sudo -u "$name" $aurhelper -S libxft-bgra-git >/dev/null 2>&1 ; }


grub(){ \
    dialog --infobox "Initiating Bootloader..." 4 40
        [ -d /sys/firmware/efi/efivars ] && pacman -S --noconfirm --needed grub efibootmgr >/dev/null 2>&1 &&
            grub-install --target=x86_64-efi --bootloader-id=AutoLinux --recheck >/dev/null 2>&1 ;
        ! [ -d /sys/firmware/efi/efivars ] && pacman -S --noconfirm --needed grub >/dev/null 2>&1 &&
            grub-install --target=i386-pc --bootloader-id=AutoLinux --force  >/dev/null 2>&1 ;
            grub-mkconfig -o /boot/grub/grub.cfg >/dev/null 2>&1 ; }                

grubtheme(){ \
	dialog --infobox "Setting Grub theme..." 4 30 
    sleep 1 && mkdir -p /boot/grub/themes/AutoLinux &&
    cp /home/$name/.local/share/wallpapers/0.jpg /boot/grub/themes/AutoLinux/wp1.jpg  >/dev/null 2>&1 
    sed -i 's/#GRUB_BACKGROUND.*/GRUB_BACKGROUND="\/boot\/grub\/themes\/AutoLinux\/wp1.jpg"/g' /etc/default/grub >/dev/null 2>&1
    sed -i 's/GRUB_BACKGROUND.*/GRUB_BACKGROUND="\/boot\/grub\/themes\/AutoLinux\/wp1.jpg"/g' /etc/default/grub >/dev/null 2>&1
    sed -i 's/GRUB_TIMEOUT=.*/GRUB_TIMEOUT=10/g' /etc/default/grub >/dev/null 2>&1
    sed -i 's/#GRUB_GFXMODE.*/GRUB_GFXMODE=1920x1080x32/g' /etc/default/grub >/dev/null 2>&1
}


finalize(){ \
	dialog --infobox "Preparing welcome message..." 4 50
    [ $edition = "1" ] && dialog --title "Time to Celebrate!" --msgbox "\\nInstallation completed successfully! Provided there were no hidden errors, all the programs and configuration files should be in place.\\n\\nTo run the new graphical environment, log out and log back in as your new user, then run the command 'startx' to start the graphical environment \\n(it will start automatically in tty1).\\n\\n Enjoy AutoLinux!   - dqYpb" 13 80 ; 
    [ $edition = "2" ] && sed -i 's/Name=.*$/Name=AutoLinux (Plasma)/g' /usr/share/xsessions/plasma.desktop && cp -r /home/$name/.local/bin/* /usr/local/bin/ &&
      dialog --title "Time to Celebrate" --msgbox "\\n                     The AutoLinux installation process has completed successfully\!\\n\\n\\n   Provided there were no hidden errors, all the programs and configuration files should be in place.\\n\\nautolinux-Plasma will automatically start up in the login manager the next time you reboot your computer.\\n\\n\\n\\n Enjoy AutoLinux!   - dqYpb" 17 110 ; }


rebootmsg(){ \
    i=10 ; i=$i ; clear
    until [ $i -lt 0 ] ; do
    echo -e " Exiting in: $i\n" | figlet -tc |lolcat && sleep 1 && clear &&
    ((i=$i-1)) ; done && umount -l /mnt && exit 0 || rebootmsg ; }



### SCRIPT BEGIN ###

check_root

installpkg dialog || err "Root priviledges are required to run this script!"

initmsg1 || err "User exited."

initmsg2 || err "User exited."

whichedition || err "User exited."

user_and_password || err "User exited."

root_user_password || err "User exited."

usercheck || err "User exited."

bootload

preinstall || err "User exited."

refreshkeys || err "Automatically refreshing Arch keyring. Consider doing so manually."

for x in curl ca-certificates base-devel archlinux-keyring hwinfo neofetch rsync git ntp zsh ; do
	dialog --title "AutoLinux Installation" --infobox "Installing '$x' which is required to install and configure other programs." 5 70
	installpkg "$x"
done

pacman-key --init >/dev/null 2>&1; pacman-key --populate >/dev/null 2>&1
dialog --title "AutoLinux Installation" --infobox "Synchronizing system time to ensure successful and secure installation of software..." 4 70
ntpdate 0.us.pool.ntp.org >/dev/null 2>&1

# newmirrors || err "User exited." 

adduserandpass || err "Adding username and/or password."

setrootpass || err "Changing root password."

sudoers "%wheel ALL=(ALL) NOPASSWD: ALL #AutoLinux"


[ -f /etc/sudoers.pacnew ] && cp /etc/sudoers.pacnew /etc/sudoers 


archlinuxinstall yay-bin


[ $edition = "1" ] && pkgsfile="https://gitlab.com/qYp/autolinux/-/raw/editions/dwm.csv" && gitbranch="dwm"

[ $edition = "2" ] && pkgsfile="https://gitlab.com/qYp/autolinux/-/raw/editions/plasma.csv" && gitbranch="plasma"

[ $edition = "3" ] && pkgsfile="https://gitlab.com/qYp/autolinux/-/raw/editions/bare.csv" && gitbranch="bare"


installationloop ; cpudrivers ; gpudrivers  
                           
[ $edition = "1" ] && xftlib

systembeepoff ; promptfix 


placeconfigs "$dotfiles" "/home/$name" "$gitbranch" && rm -rf "/home/$name/.git"
          
chshell || err "Changing default shell for root and "$name"."


mkdir -p /etc/X11/xinit/xinitrc.d >/dev/null 2>&1 &&
    [ -f /home/$name/.config/shell/profile ] && cat /home/$name/.config/shell/profile > /etc/zsh/zprofile >/dev/null 2>&1
    [ -f /home/$name/.config/x11/xinitrc ] && cat /home/$name/.config/x11/xinitrc > /etc/X11/xinit/xinitrc >/dev/null 2>&1

[ -d /root/.config ] && mv /root/.config /root/.config-old >/dev/null 2>&1 
[ -d /root/.local/ ] && mv /root/.local/ /root/.local-old >/dev/null 2>&1
    ln -s /home/$name/{.config,.local/} /root >/dev/null 2>&1 &&
    cp /home/$name/.config/shell/profile /root/.zprofile >/dev/null 2>&1

[ $edition = "1" ] && cp /home/$name/.local/src/dwm/dwm /usr/bin/dwm && 
    cp /home/$name/.local/src/dwm/dwm /usr/bin/AutoLinux-dwm

[ $edition = "2" ] && pacman -S plasma-desktop plasma-meta  --noconfirm   >/dev/null 2>&1 && 
    cp /usr/bin/startplasma-x11 /usr/bin/AutoLinux-plasma  >/dev/null 2>&1

grep -q "OTHER_OPTS='-a pulseaudio -m alsa_seq -r 48000'" /etc/conf.d/fluidsynth ||
	echo "OTHER_OPTS='-a pulseaudio -m alsa_seq -r 48000'" >> /etc/conf.d/fluidsynth

[ "$loader" = "0" ] && grubtheme && grub ; pkill -15 -x 'pulseaudio' ; 
    sudo -u "$name" pulseaudio --start ; system_config ; finalize ; 
    clear ; [ $edition = '1' ] || [ $edition = '2' ] && skell


#########################################################################################################################################################################################
#########################################################################################################################################################################################
